[package]
name = "davy"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "davy"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
base64 = "0.22"
chrono = { version = "0.4", default-features = true }
clap = { version = "4.5", features = ["derive", "env", "wrap_help"] }
users = "0.11"
